apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: pod-affinity
  namespace: kafka
spec:
  kafka:
    version: 2.8.0
    replicas: 3
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 100m
        memory: 100Mi
    jvmOptions:
      "-Xmx": "1500m"
      "-Xms": "256m"
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.8"
      inter.broker.protocol.version: "2.8"
    storage:
      type: ephemeral
    template:
      pod:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: strimzi.io/cluster
                      operator: In
                      values:
                        - pod-affinity
                topologyKey: "kubernetes.io/hostname"
  zookeeper:
    replicas: 3
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 100m
        memory: 100Mi
    jvmOptions:
      "-Xmx": "1500m"
      "-Xms": "256m"
    storage:
      type: ephemeral
    template:
      pod:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: strimzi.io/name
                      operator: In
                      values:
                        - pod-affinity-zookeeper
                topologyKey: "kubernetes.io/hostname"
