apiVersion: v1
kind: Service
metadata:
  name: postgres-service-2
  namespace: kafka
  labels:
    app: postgres-2
spec:
  type: ClusterIP
  ports:
   - port: 5432
  selector:
   app: postgres-2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-2
  namespace: kafka
spec:
  selector:
    matchLabels:
      app: postgres-2
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-2
    spec:
      containers:
        - name: postgres
          image: tmaxcloudck/postgres-cron:b5.0.0.1
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
          - name: TZ
            value: 'Asia/Seoul'
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret-2
                key: POSTGRES_PASSWORD
          resources:
            limits:
              cpu: "500m"
              memory: "500Mi"
            requests:
              cpu: "300m"
              memory: "100Mi"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: data
              subPath: postgres
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: postgres-data-2
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-data-2
  namespace: kafka
spec:
  #storageClassName: csi-cephfs-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret-2
  namespace: kafka
type: Opaque
data:
  POSTGRES_PASSWORD: dG1heA==
