apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kafka-bindable-operator-leader-election-rolebinding
  namespace: kafka
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kafka-bindable-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: strimzi-cluster-operator
  namespace: kafka