apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kafka-bindable-operator-leader-election-role
  namespace: kafka
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete