# mysql 실행 후 접속하여 아래 명령어 실행
# mysql> SET GLOBAL binlog_format = 'ROW';
# mysql> SET GLOBAL server_id = 184054;

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: kafka
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: mypassword
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mycnf
          mountPath: /etc/mysql/my.cnf
          subPath: my.cnf
      volumes:
      - name: mycnf
        configMap:
          name: mycnf
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: kafka
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
---
apiVersion: v1
kind: Secret
metadata:
  name: my-sql-credentials
  namespace: kafka
type: Opaque
data:
  mysql_username: cm9vdA==
  mysql_password: bXlwYXNzd29yZA==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mycnf
  namespace: kafka
data:
  my.cnf: |
    [mysqld]
    log-bin=mysql-bin
    max_binlog_size=1G
    expire_logs_days=30 
