apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
  namespace: kafka
spec:
  kafka:
    version: 3.0.0
    replicas: 1
    resources:
      limits:
        cpu: 1000m
        memory: 1536Mi
      requests:
        cpu: 100m
        memory: 100Mi
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.8"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 100Gi
        deleteClaim: false
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 100Gi
      deleteClaim: false
  entityOperator:
    topicOperator:
      resources:
        limits:
          cpu: 1000m
          memory: 1536Mi
        requests:
          cpu: 100m
          memory: 100Mi
    userOperator:
      resources:
        limits:
          cpu: 1000m
          memory: 1536Mi
        requests:
          cpu: 100m
          memory: 100Mi
