apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: kafka-sink-connector-mysql-11
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-connect-cluster
spec:
  class: io.confluent.connect.jdbc.JdbcSinkConnector
  tasksMax: 1
  config:
    connection.url: "jdbc:mysql://172.22.6.11:3306/tmax?enabledTLSProtocols=TLSv1.2"
    connection.user: "admin"
    connection.password: "admin"
    topics: "jdbc-connector-developer"
    # topics.regex: "jdbc-connector-*"
    table.name.format: "${topic}"
    auto.create: "true"
    auto.evolve: "true"
    delete.enabled: "false"
    #insert.mode: "upsert"
    #pk.mode: "record_key"
    # pk.fields: "id"
    #key.converter: "org.apache.kafka.connect.json.JsonConverter"
    #key.converter.schemas.enable: "true"
    #value.converter: "org.apache.kafka.connect.json.JsonConverter"
    #value.converter.schemas.enable: "true"
    transforms: dropPrefix,unwrap
    transforms.dropPrefix.type: org.apache.kafka.connect.transforms.RegexRouter
    transforms.dropPrefix.regex: jdbc\-connector\-(.*)
    transforms.dropPrefix.replacement: $1
    transforms.unwrap.type: io.debezium.transforms.ExtractNewRecordState
    transforms.unwrap.drop.tombstones: "false"

    database.history.kafka.bootstrap.servers: "bootstrap.172.22.6.13.nip.io:443"
    #    database.history.kafka.topic: "schema-changes.inventory"
    database.history.producer.security.protocol: "SSL"
    database.history.producer.ssl.keystore.location: "/opt/kafka/connect-certs/kafka-connect-jks/keystore.jks"
    database.history.producer.ssl.keystore.password: "tmax@23"
    database.history.producer.ssl.truststore.location: "/opt/kafka/connect-certs/kafka-connect-jks/truststore.jks"
    database.history.producer.ssl.truststore.password: "tmax@23"
    database.history.producer.ssl.key.password: "tmax@23"
    database.history.consumer.security.protocol: "SSL"
    database.history.consumer.ssl.keystore.location: "/opt/kafka/connect-certs/kafka-connect-jks/keystore.jks"
    database.history.consumer.ssl.keystore.password: "tmax@23"
    database.history.consumer.ssl.truststore.location: "/opt/kafka/connect-certs/kafka-connect-jks/truststore.jks"
    database.history.consumer.ssl.truststore.password: "tmax@23"
    database.history.consumer.ssl.key.password: "tmax@23"
